### PR TITLE
Add `from` and `fromNow` methods

### PR DESCRIPTION
**Pull request by shaungrady**
Closes https://github.com/smallwins/spacetime/issues/46

``` javascript
const a = spacetime('November 11, 1999 11:11:11', 'Canada/Eastern');
const b = spacetime('December 12, 2000 12:12:12', 'Canada/Eastern');

a.from(b);
// {
//   diff: {
//     years: -1,
//     months: -1,
//     days: -1,
//     hours: -1,
//     minutes: -1,
//     seconds: -1
//   },
//   rounded: '1 year ago',
//   qualified: '1 year ago',
//   precise: '1 year, 1 month ago'
// }

b.from(a);
// {
//   diff: {
//     years: 1,
//     months: 1,
//     days: 1,
//     hours: 1,
//     minutes: 1,
//     seconds: 1
//   },
//   rounded: 'in 1 year',
//   qualified: 'in 1 year',
//   precise: 'in 1 year, 1 month'
// }
```
``` javascript
const past = spacetime.now()
  .subtract(23, 'months')
  .subtract(23, 'seconds')
  
past.fromNow()
// {
//   diff: {
//     years: -1,
//     months: -11,
//     days: -0,
//     hours: -0,
//     minutes: -0,
//     seconds: -23
//   },
//   rounded: '2 years ago',
//   qualified: 'almost 2 years ago',
//   precise: '1 year, 11 months ago'
// }

### CODE REVIEW

**Comment by spencermountain** [comment]
niice!
thank you!

**Comment by spencermountain** [comment]
hey, what are your feelings about me renaming this to `.since()`?
I suppose `.since()` with an empty param would assume `fromNow()`?
lemme know what you think,
cheers

**Comment by shaungrady** [comment]
I like it 👍

**Comment by spencermountain** [comment]
hey - so after i changed it to `.since()` it became apparent that it now reads like 'time since B', which is sorta like asking 'how much time has passed since this previous time' ... so I reversed the before/after logic to make it `after.since(before)`... not sure if this was a good idea or not. I think it may not be..

I also added support for the main input parsing of the input, so it's now can it do this stuff:
```js
spacetime('March 12th 2018').since('March 10th 2018')
// {diff:{days:2} ... }
spacetime('new years eve').since('christmas')
// {diff:{days:6} ... }
```

you're also right about the non-obvious calendar-centric behaviour of `.diff()`. I added some explanation for this in the readme.

will do a release tonight, `v4.0.0`.
thanks!

**Comment by shaungrady** [comment]
Yeah, might not be the best idea. Especially since it's touted that Spacetime has a Moment-like API. Maybe `since` can be an alias of `from` that reverses the logic?

**Comment by spencermountain** [comment]
yeah, good idea.
here's both, as of `4.0.1`
cheers!
https://runkit.com/spencermountain/5aa701633c79ae0012687182

**Pull request merged**
